### ISSUE TITLE
Default formatter

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/arkimet-postprocessor-suite#3]
Since, AFAIK, from arkiweb interface no options are available for json plugin and json format is more compact and readable than geojson, could we make `formatter="dbamsg dump --json"` the default?

**Comment by edigiacomo** [comment]
For backward compatibility, I would prefer not to change the default behaviour of the postprocessor. We could add an option in arkiweb interface.

Note that `json` postprocessor without `LON LAT` optional arguments is a bit risky in GRIB datasets (the response can be huge) and I was thinking to drop the support for this format (I think that @pat1 agrees with me), unless you need it (but not in my servers :D ). For GRIB data, we could add `dbajson` to the supported formats in `singlepoint` postprocessor and update the arkiweb interface to handle it.

**Comment by dcesari** [comment]
Forgot to say, it's for a bufr dataset (model vertical profiles).

**Comment by edigiacomo** [comment]
Thanks Davide :) In this case an option in arkiweb interface would solve the issue? The default option value could be `dbajson`

**Comment by dcesari** [comment]
Great!!

**Comment by edigiacomo** [comment]
Fixed in `arkiweb-0.24`.
