### ISSUE TITLE
travis and copr integration

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet-postprocessor-suite#7]
long story short, to permit travis/copr integration we need:

- [x] a single `configure.ac` (by @edigiacomo)
- [x] a single specfile (by @brancomat)
- [x] all the rest (`travis.yml` and `travis-build.sh` script, copr hook, etc)
- [x] `bufr2json` in copr
- [x] (optional) before closing this, another enhancement issue giving back the possibility to split in single packages (via `configure.ac` options)

**Comment by edigiacomo** [comment]
See #8 for the last point.
