### ISSUE TITLE
Adapt to new libsim and arkimet

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/arkimet-postprocessor-suite#9]
Some modernization required: 
 * test-singlepoint fails because of --inline not supported by arki-scan
 * getpoint and subarea make use of obsolete/ambiguous libsim arguments
ghe pensi mi.

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.

**Comment by dcesari** [comment]
Ehm, queste modifiche sono rimaste in una PR https://github.com/ARPA-SIMC/arkimet-postprocessor-suite/pull/10 mai chiusa sebbene tu l'avessi approvata, siccome è passato del tempo, richiedo una riapprovazione per il merge.

Sorry

**Comment by edigiacomo** [comment]
Scusami tu, potevo fare io il merge a suo tempo!
